services:
  - type: web
    name: journey-backend
    runtime: python311
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 8 --timeout 0 --access-logfile - --error-logfile - app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
